version: "3"

services:
  hfu_redis:
    image: "redis:6.2.6-alpine"
    container_name: hfu_redis
    hostname: hfu_redis
    env_file:
      - .env.development
    command: >
      --requirepass ${REDIS_PASSWORD}
    restart: "always"

  hfu_db:
    image: postgres:12-bullseye
    container_name: hfu_db
    restart: always
    hostname: "hfu_db"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env.development
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p $POSTGRES_PORT

  hfu_server:
    container_name: hfu_server
    env_file:
      - .env.development
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: "always"
    volumes:
      - ./server:/app
      - /app/node_modules/
    depends_on:
      - "hfu_db"
      - "hfu_redis"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["yarn", "dev"]
