version: "3"

services:
  hfu_redis:
    image: "redis:6.2.6-alpine"
    container_name: hfu_redis
    hostname: hfu_redis
    env_file:
      - .env
    command: >
      --requirepass ${REDIS_PASSWORD}
    restart: "always"

  hfu_db:
    image: postgis/postgis:12-3.2
    container_name: hfu_db
    restart: always
    hostname: "hfu_db"
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    command: -p $POSTGRES_PORT

  hfu_server:
    container_name: hfu_server
    env_file:
      - .env
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: "always"
    depends_on:
      - "hfu_db"
      - "hfu_redis"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: ["yarn", "start"]
